title: <p align="center"> Uma Hyndavi Simhadri </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/uma-hyndavi-72a455135/">LinkedIn</a> |
  <a href="https://github.com/UmaHyndavi">GitHub</a>
  
  <br>   
  I worked as a Mainframe Developer at Tata consultancy services.For 1+ years of experience. 
  <br>
  </p>



theme: jekyll-theme-minimal
